apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server-cluster
#  labels:
#    app: cassandra
#    version: 3.11
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-server
          image: nicolas2lee/kafka
          command: [/opt/kafka_2.12-2.1.0/bin/kafka-server-start.sh]
          args: ["/opt/kafka_2.12-2.1.0/config/server.properties", "--override", "zookeeper.connect=zookeeper:2181"]
          ports:
            - containerPort: 9092


