---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-server-cluster
#  labels:
#    app: cassandra
#    version: 3.11
spec:
  serviceName: kafka-svc
  selector:
    matchLabels:
      app: kafka
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-server
          image: nicolas2lee/kafka
          ports:
            - containerPort: 9092
          command:
            - bash
            - "-c"
            - "/opt/kafka_2.12-2.1.0/bin/kafka-server-start.sh /opt/kafka_2.12-2.1.0/config/server.properties \
          --override zookeeper.connect=zookeeper:2181 \
          --override broker.id=${HOSTNAME##*-}"
---

apiVersion: v1
kind: Service
metadata:
  name: afka-svc
  labels:
    app: kafka
spec:
  ports:
    - name: server
      port: 9092
      protocol: TCP
  selector:
    app: kafka
