apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server-cluster
#  labels:
#    app: cassandra
#    version: 3.11
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-server
          image: confluent/kafka
          ports:
            - containerPort: 9092

